[profile.default]
src = "contracts"
out = "artifacts"
cache_path = 'cache'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
solc_version = '0.8.30'
libs = [
    "lib",
    "node_modules",
    "dependencies",
]
fs_permissions = [
    { access = "read", path = "deployment/chain-config/" },
    { access = "read", path = "deployment/deploys/" },
    { access = "read-write", path = "deployment/output-internal" },
    { access = "read", path = "deployment/cuts/" },
    { access = "read", path = "artifacts/" }
]
ffi = true
via_ir = true

[dependencies]
"@openzeppelin-contracts" = "5.5.0"
forge-std = "1.10.0"
flare-periphery = "0.1.38"
"@uniswap-v3-core" = "1.0.1"
"@uniswap-v3-periphery" = "1.4.4"


[soldeer]
remappings_generate = false
remappings_regenerate = false
remappings_version = false
remappings_location = "txt"
recursive_deps = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
